from pathlib import Path
import hashlib,json
import numpy as np
from PIL import Image
BASE=Path(__file__).resolve().parent
ROOT=BASE.parents[4]
RASTER=ROOT/'native/client/assets/raster'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rec(p,role):
    raw=p.read_bytes();binary=p.suffix.lower() in ('.png','.gif')
    return {'path':p.relative_to(ROOT).as_posix(),'role':role,'sha256':hashlib.sha256(raw if binary else raw.replace(b'\r\n',b'\n')).hexdigest(),'hash_policy':'raw_binary' if binary else 'canonical_lf_crlf_to_lf_only'}
idle=RASTER/'runtime/raider_ne.png';manifest=BASE/'import.json';report=BASE/'import.provenance.json'
records=json.loads(report.read_text())['assets'];colors=set()
for i,r in enumerate(records):
    p=BASE/f'raider_walk{i}_ne.png';a=np.array(Image.open(p).convert('RGBA'))
    assert sha(p)==r['sha256']
    assert r['before_resize']==r['placed_size']
    assert r['anchor_px']==[40,96]
    assert set(np.unique(a[:,:,3])).issubset({0,255})
    colors.update(map(tuple,a[:,:,:3][a[:,:,3]>0]))
assert len(colors)==32
originals={1:'exec-d656e9ab-483d-4085-8bd5-4034d304fb7c.png',2:'exec-27b45f72-5e9d-41f6-81db-9b17f5882137.png'}
for v in (1,2):
    source=RASTER/f'source/raider-walk-ne-v{v}.png';prompt=RASTER/f'prompts/raider-walk-ne-v{v}.txt'
    refs=[]
    if v==2:refs.append({'path':'native/client/assets/raster/source/raider-walk-ne-v1.png','sha256':sha(RASTER/'source/raider-walk-ne-v1.png'),'role':'Edit target: repair legs of phases2/3 only; preserve the remaining poses and upper bodies.'})
    refs.append({'path':idle.relative_to(ROOT).as_posix(),'sha256':sha(idle),'role':'Accepted NE raider identity, rear upper-right camera, anatomy, clothing and anatomical-right axe reference. Never copy its idle pose in the correction.'})
    data={'version':1,'tool':'built-in image_gen','model_variant':'Not selectable or identified by this tool; no variant asserted.','use_case':'stylized-concept' if v==1 else 'identity-preserve','source':source.relative_to(ROOT).as_posix(),'source_raw_sha256':sha(source),'dimensions':[1536,1024],'source_mode':'RGBA' if v==1 else 'RGB','generated_original':'C:/Users/Alex/.codex/generated_images/01a0896f-29de-7452-bb4b-6fb64351c1eb/'+originals[v],'prompt':prompt.relative_to(ROOT).as_posix(),'prompt_raw_sha256':sha(prompt),'submitted_prompt':prompt.read_text().rstrip('\n'),'references':refs,'all_references_viewed_before_call':True,
    'recipe':{'primary_source':'https://www.reddit.com/r/aigamedev/comments/1wbmvnm/gpt_image_25_nailed_a_16_frame_combat_sprite_sheet/?sort=top','original_read':'Opened the original post with web.run in this task; read its exact prompt, creator claim and critical replies identifying limb swaps and poor temporal progression.','published_prompt':'Make a simplified 128px pixel art combat motion sprite sheet of this character, transparent background if you can, arrange it 4x4.','adaptation':'Retain one supplied character reference, simplified pixel construction, one motion sheet and separate GIF assembly. Change the motion to six chronological NE walking poses in3x2, around64 logical body pixels. Add explicit opposite contact/passing legs and equipment hand to address observed prior gait/weapon failures. V2 changes only the failed legs in phases2/3 using the original identity alongside the first sheet.','local_prior_inspected':['native/client/assets/raster/source/raider-walk-sw-axe-v3.png','native/client/assets/raster/runtime/raider_walk0_sw.png','native/client/assets/raster/prompts/raider-walk-sw-d2poses-v1.txt','native/client/assets/raster/prompts/raider-walk-sw-axe-v3.txt'],'prior_images_not_supplied':'SW front-facing references were inspected for identity/equipment history, not sent as NE pose inputs. No external D2 image was supplied or copied.','claim_boundary':'The creator did not demonstrate this adult raider NE walk or our Pixel Respecter reconstruction. Their named model/access path is not attributed to our built-in call.'},
    'observations':{'v1_failure':'Phases2/3 repeated the long screen-left trailing leg; rejected as a complete alternating cycle. Real alpha existed but included a faint partial-alpha halo.','v2_result':'Phases2/3 now give the opposite screen-right foreground leg and raised/receding opposite boot. The edit changed non-target cells and painted an opaque checker; only corrected phases2/3 are selected.','selected_composition':'V1 phases0,1,4,5 plus V2 phases2,3. No body repainting or mirrored pose substitution.','identity':'Rear upper-right view, tied dark hair, blue-charcoal clothing, ochre sash, brown boots/bracers; axe stays in anatomical-right/screen-right hand. Walk silhouette is narrower and its blade slimmer/near edge-on compared with idle.','phase_limit':'Six key poses with distinct opposite contacts and passing legs; phases5/0 remain close, and arms/torso have modest motion. This is a provisional gait, not a biomechanical or production-motion guarantee.'},
    'conversion':{'manifest':manifest.relative_to(ROOT).as_posix(),'manifest_raw_sha256':sha(manifest),'report':report.relative_to(ROOT).as_posix(),'report_raw_sha256':sha(report),'engine':'Actual external Pixel Respecter workspace.reconstruct and shared palettes.reduce_colors via import_assets.py','cell_size':7,'canvas':[80,96],'pivot':[40,96],'source_origin':[315,483],'column_stride':455,'row_stride':490,'shared_colors':32,'scale_policy':'One common scale and source origin pattern; no per-pose fitting or centering. Common baseline was lowered two pixels after idle-transition review; phase-specific lift was preserved.','alpha':'V1 crisp reconstruction uses its actual alpha and alpha_floor128. V2 border-connected cleanup uses RGB160 and tolerance100. No local windows or selected chromatic pixels removed. See selected/alpha-audit.json.'},
    'acceptance':'Root viewed native1x/3x and source alpha comparison; approved provisional production integration with smaller-axe/narrower-body caveats, pending actual game check. Selected source/manifest/PNG/report bytes are frozen.','ownership':'Only new raider-walk-ne sources/prompts and raider-walk-ne-candidates folder. No runtime/catalog/main edits or git operations.'}
    prompt.with_suffix('.provenance.json').write_text(json.dumps(data,indent=2)+'\n')
review={'status':'root_native_review_approved_provisional_production_integration_pending_game_check','frame_count':6,'order':[0,1,2,3,4,5],'phases':['right-foot contact with left trailing','left passing over right support','left reach/opposite-leg opening','left contact with right trailing','right passing over left support','right reach back toward opening contact'],'body_view':'Actual back faces upper-right; face and mask remain hidden.','equipment':'Baked anatomical-right/screen-right axe; ordinary monster sprite, no hero overlay.','canvas':[80,96],'pivot':[40,96],'cell_size':7,'source_origin':[315,483],'column_stride':455,'row_stride':490,'visible_body_heights':[56,56,57,58,53,57],'visible_alpha_bottoms':[95,95,96,95,92,95],'idle_body_height':57,'idle_alpha_bottom':96,'palette':'One shared32-color palette; cloth blue-charcoal, natural bronze/leather/ochre.','preview_frame_ms':100,'preview_loop_ms':600,'reviews':['Original source and focused correction inspected','Native1x and integer3x ordered strips, including idle transition, reviewed on dark and light backgrounds','Source/cleaned comparison inspected for hair, arms and leg gaps','Animated browser preview rendered at1x/3x; opposite-contact phase3 inspected','Root explicitly accepted provisional integration after viewing native1x/3x and alpha comparison'],'limits':['Smaller near edge-on axe blade than accepted idle','Narrower walking body/stance than idle','Close phase5 to0 transition and modest arm/torso animation','Actual game movement, frame timing, occlusion and frame budget remain unverified in this lane'],'source_calls':2,'further_generation':'None after root acceptance','runtime_modified_by_this_lane':False}
(BASE/'acceptance-review.json').write_text(json.dumps(review,indent=2)+'\n')
deps={'version':1,'scope':'Frozen raider NE6 candidate approved for provisional integration; all paths repository-relative.','hash_policy':'Text canonicalizes CRLF to LF only; binary uses raw bytes. Historical generation raw hashes are not rewritten.','active_inputs':[rec(RASTER/f'source/raider-walk-ne-v{v}.png','selected generated source: phases0/1/4/5' if v==1 else 'selected leg correction: phases2/3') for v in (1,2)],'active_recipes':[rec(manifest,'complete selected candidate recipe'),rec(ROOT/'native/tools/raster/import_assets.py','actual Pixel Respecter adapter')],'historical_provenance':[rec(idle,'accepted identity reference')]+[rec(RASTER/f'prompts/raider-walk-ne-v{v}{s}','exact prompt or generation/reference provenance') for v in (1,2) for s in ('.txt','.provenance.json')]+[rec(report,'actual candidate import and external engine fingerprint report')],'review_evidence':[rec(BASE/n,'native or alpha review evidence') for n in ('acceptance-review.json','native-review.json','alpha-audit.json','alpha-source-comparison.png','idle-walk-idle-1x.png','idle-walk-idle-3x.png','walk-preview.gif')],'selected_outputs':[rec(BASE/f'raider_walk{i}_ne.png','frozen selected candidate frame') for i in range(6)],'external_project':{'path':'Z:/Code/Python/pixel-perfecter','vendored':False,'fingerprints_in':report.relative_to(ROOT).as_posix()},'reproduction':'Run existing import_assets.py with selected/import.json. Two source PNGs and the complete manifest reproduce the frozen six-frame batch; no rejected candidate PNG is needed.'}
(BASE/'dependencies.json').write_text(json.dumps(deps,indent=2)+'\n')
staging=[RASTER/f'source/raider-walk-ne-v{v}.png' for v in (1,2)]+[RASTER/f'prompts/raider-walk-ne-v{v}{s}' for v in (1,2) for s in ('.txt','.provenance.json')]+[p for p in BASE.iterdir() if p.is_file() and p.suffix.lower() in ('.json','.py','.png','.gif','.html')]
(BASE/'staging-paths.txt').write_text('\n'.join(sorted(set(p.relative_to(ROOT).as_posix() for p in staging)))+'\n'+(BASE/'staging-paths.txt').relative_to(ROOT).as_posix()+'\n')
print(json.dumps({'frozen_frames':6,'shared_colors':len(colors),'dependency_file':(BASE/'dependencies.json').relative_to(ROOT).as_posix(),'generation_provenance_records':2,'status':review['status']}))
