#!/usr/bin/env python3
"""TASK-0160 negative-test harness for native/tools/verify_native_visual_kit.py.

Runs the committed visual-kit validator against focused synthetic fixtures
under ./fixtures (a positive mini kit plus one mutation per contract rule),
plus an independent hand-written golden-oracle test of the generator layout,
a determinism test, a read-only proof for --check, and regeneration-mode
controls. Python 3 stdlib only; never touches the network or any port.
"""

from __future__ import annotations

import hashlib
import importlib.util
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
TOOL_PATH = REPO_ROOT / "native" / "tools" / "verify_native_visual_kit.py"
FIXTURES_DIR = HERE / "fixtures"

SOLO_SVG = """<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <polygon points="0,0 10,0 0,10" fill="#102030"/>
  <polyline points="1,1 2,2" fill="none" stroke="#404040" stroke-width="2" stroke-linejoin="round"/>
</svg>
"""

SOLO_MANIFEST_SKELETON = """{
  "generatorVersion": "task0147-gen-2",
  "viewBox": {
    "width": 64,
    "height": 64
  },
  "roles": [
    {
      "role": "solo",
      "motifs": [
        {
          "motif": "default",
          "symbol": "solo_one",
          "source": "native/client/assets/svg/solo.svg",
          "palette": [
            "#102030",
            "#404040"
          ]
        }
      ]
    }
  ]
}
"""

EXPECTED_SOLO_HEADER = """// Generated by orchestration/tasks/TASK-0141-procedural-native-visual-kit/generate-assets.mjs version task0147-gen-2. DO NOT EDIT.
#pragma once

#include <cstdint>

namespace verdigris::visual_kit {

inline constexpr char kKitVersion[] = "task0147-gen-2";

enum class ShapeKind : int32_t {
  Polygon,
  Polyline,
  Circle,
  Ellipse,
};

struct Color {
  float r;
  float g;
  float b;
  float a;
};

struct Shape {
  ShapeKind kind;
  int32_t point_begin;
  int32_t point_end;
  int32_t fill;
  int32_t stroke;
  float stroke_width;
  float cx;
  float cy;
  float rx;
  float ry;
};

struct Symbol {
  const char* role;
  const char* motif;
  const char* source;
  float width;
  float height;
  int32_t shape_begin;
  int32_t shape_end;
};

inline constexpr Color kColors[] = {
    {0.06f, 0.13f, 0.19f, 1.f},
    {0.25f, 0.25f, 0.25f, 1.f},
};

inline constexpr float kPoints[] = {
    0.f, 0.f, 10.f, 0.f, 0.f, 10.f, 1.f, 1.f,
    2.f, 2.f,
};

inline constexpr Shape kShapes[] = {
    {ShapeKind::Polygon, 0, 3, 0, -1, 0.f, 0.f, 0.f, 0.f, 0.f},
    {ShapeKind::Polyline, 3, 5, -1, 1, 2.f, 0.f, 0.f, 0.f, 0.f},
};

inline constexpr Symbol kSymbols[] = {
    {"solo", "default", "native/client/assets/svg/solo.svg", 64.f, 64.f, 0, 2},
};

inline constexpr int32_t kSymbolCount = 1;

}
"""

CLI_CASES = [
    ("valid-mini-kit", 0, frozenset()),
    ("missing-source", 1, frozenset({"MISSING_SOURCE"})),
    ("duplicate-entry", 1, frozenset({"DUPLICATE_ENTRY"})),
    ("unknown-file", 1, frozenset({"UNKNOWN_SVG_FILE"})),
    ("unsafe-svg", 1, frozenset({"UNSAFE_SVG"})),
    ("malformed-svg", 1, frozenset({"MALFORMED_SVG"})),
    ("palette-mismatch", 1, frozenset({"PALETTE_MISMATCH"})),
    ("stale-header", 1, frozenset({"STALE_HEADER"})),
    ("ordering-mismatch", 1, frozenset({"ORDERING_MISMATCH", "STALE_HEADER"})),
]


def load_validator_module():
    spec = importlib.util.spec_from_file_location("verify_native_visual_kit_under_test", TOOL_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load validator module from {TOOL_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def tree_digests(root: Path) -> dict[str, str]:
    digests: dict[str, str] = {}
    for path in sorted(root.rglob("*")):
        if path.is_file():
            key = path.relative_to(root).as_posix()
            digests[key] = hashlib.sha256(path.read_bytes()).hexdigest()
    return digests


def emitted_codes(stdout: str) -> set[str]:
    return {line.split(":", 1)[0].removeprefix("FAIL ").strip() for line in stdout.splitlines() if line.startswith("FAIL ")}


class Results:
    def __init__(self) -> None:
        self.passed = 0
        self.failed = 0

    def record(self, name: str, ok: bool, detail: str = "") -> None:
        if ok:
            self.passed += 1
            print(f"PASS {name}")
        else:
            self.failed += 1
            print(f"FAIL {name}" + (f" :: {detail}" if detail else ""))


def run_cli_cases(results: Results) -> None:
    for name, expected_exit, expected_codes in CLI_CASES:
        fixture_root = FIXTURES_DIR / name
        completed = subprocess.run(
            [sys.executable, str(TOOL_PATH), "--check", "--root", str(fixture_root)],
            capture_output=True,
            text=True,
        )
        problems: list[str] = []
        if completed.returncode != expected_exit:
            problems.append(f"exit {completed.returncode} != expected {expected_exit}")
        actual_codes = emitted_codes(completed.stdout)
        missing_codes = expected_codes - actual_codes
        if missing_codes:
            problems.append(f"missing failure codes {sorted(missing_codes)}")
        if name == "valid-mini-kit" and "verify_native_visual_kit: OK" not in completed.stdout:
            problems.append("positive control did not print OK summary")
        results.record(f"cli/{name}", not problems, "; ".join(problems))


def run_oracle_case(results: Results, validator) -> None:
    with tempfile.TemporaryDirectory(prefix="task0160-oracle-") as tmp:
        root = Path(tmp)
        assets = root / "native" / "client" / "assets"
        (assets / "svg").mkdir(parents=True)
        (assets / "svg" / "solo.svg").write_text(SOLO_SVG, encoding="utf-8", newline="\n")
        (assets / "manifest.json").write_text(SOLO_MANIFEST_SKELETON, encoding="utf-8", newline="\n")

        report = validator.Report()
        entries = validator.load_entries(root, report)
        if entries is None:
            results.record("oracle/solo-golden-header", False, f"entries failed to load: {report.failures}")
            return
        parsed = validator.collect_svgs(root, entries, report)
        derived = validator.derive_all(entries, parsed, report)
        if derived is None:
            results.record("oracle/solo-golden-header", False, f"derivation failed: {report.failures}")
            return
        header_ok = derived[1] == EXPECTED_SOLO_HEADER.encode("utf-8")
        manifest_ok = derived[0] == SOLO_MANIFEST_SKELETON.encode("utf-8")
        detail = ""
        if not header_ok:
            detail += f"header mismatch; first divergence: {next((chr(a) + '|' + chr(b) for a, b in zip(derived[1], EXPECTED_SOLO_HEADER.encode('utf-8')) if a != b), 'length')}"
        if not manifest_ok:
            detail += f"; manifest mismatch ({len(derived[0])}B vs {len(SOLO_MANIFEST_SKELETON.encode('utf-8'))}B)"
        results.record("oracle/solo-golden-header", header_ok, detail)
        results.record("oracle/solo-golden-manifest", manifest_ok, detail)


def run_determinism_case(results: Results, validator) -> None:
    fixture_root = FIXTURES_DIR / "valid-mini-kit"
    report_a = validator.Report()
    entries_a = validator.load_entries(fixture_root, report_a)
    parsed_a = validator.collect_svgs(fixture_root, entries_a, report_a)
    derived_a = validator.derive_all(entries_a, parsed_a, report_a)
    derived_b = validator.derive_all(entries_a, parsed_a, report_a)
    fresh_report = validator.Report()
    entries_b = validator.load_entries(fixture_root, fresh_report)
    parsed_b = validator.collect_svgs(fixture_root, entries_b, fresh_report)
    derived_c = validator.derive_all(entries_b, parsed_b, fresh_report)
    ok = (
        derived_a is not None
        and derived_a == derived_b == derived_c
        and report_a.ok
        and fresh_report.ok
    )
    results.record("determinism/two-pass-and-fresh-parse-equal", bool(ok))


def run_readonly_case(results: Results) -> None:
    fixture_root = FIXTURES_DIR / "valid-mini-kit"
    before = tree_digests(fixture_root)
    completed = subprocess.run(
        [sys.executable, str(TOOL_PATH), "--check", "--root", str(fixture_root)],
        capture_output=True,
        text=True,
    )
    after = tree_digests(fixture_root)
    ok = completed.returncode == 0 and before == after and "WROTE" not in completed.stdout
    results.record("readonly/check-leaves-tree-byte-identical", bool(ok))


def run_regeneration_cases(results: Results) -> None:
    with tempfile.TemporaryDirectory(prefix="task0160-regen-") as tmp:
        refused_root = Path(tmp) / "refused"
        shutil.copytree(FIXTURES_DIR / "unsafe-svg", refused_root)
        before = tree_digests(refused_root)
        completed = subprocess.run(
            [sys.executable, str(TOOL_PATH), "--regenerate", "--root", str(refused_root)],
            capture_output=True,
            text=True,
        )
        after = tree_digests(refused_root)
        ok = completed.returncode == 1 and before == after and "refused" in completed.stdout
        results.record("regen/refuses-unsafe-kit-without-writes", bool(ok))

        repair_root = Path(tmp) / "repair"
        shutil.copytree(FIXTURES_DIR / "palette-mismatch", repair_root)
        repair_run = subprocess.run(
            [sys.executable, str(TOOL_PATH), "--regenerate", "--root", str(repair_root)],
            capture_output=True,
            text=True,
        )
        verify_run = subprocess.run(
            [sys.executable, str(TOOL_PATH), "--check", "--root", str(repair_root)],
            capture_output=True,
            text=True,
        )
        ok = repair_run.returncode == 0 and verify_run.returncode == 0 and "OK" in verify_run.stdout
        results.record("regen/repairs-stale-manifest-then-check-passes", bool(ok))


def main(argv: list[str]) -> int:
    if argv:
        print(f"usage: {Path(__file__).name} takes no arguments", file=sys.stderr)
        return 2
    print(f"validator under test: {TOOL_PATH}")
    results = Results()
    run_cli_cases(results)
    validator = load_validator_module()
    run_oracle_case(results, validator)
    run_determinism_case(results, validator)
    run_readonly_case(results)
    run_regeneration_cases(results)
    total = results.passed + results.failed
    print(f"{total} tests: {results.passed} passed, {results.failed} failed")
    return 0 if results.failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
