#pragma once

// Generated by both supported build paths, embedded in the executable.
#if __has_include("verdigris_build_generated.hpp")
#include "verdigris_build_generated.hpp"
#endif
#ifndef VERDIGRIS_BUILD_ID
#define VERDIGRIS_BUILD_ID "unknown"
#endif
#ifndef VERDIGRIS_BUILD_DIRTY
#define VERDIGRIS_BUILD_DIRTY 1
#endif
