"""Reproduce the native inventory imports without modifying WIZARD originals."""
import argparse, hashlib, json, pathlib, subprocess
p = argparse.ArgumentParser()
p.add_argument('wizard', type=pathlib.Path)
a = p.parse_args()
root = pathlib.Path(__file__).resolve().parents[2]
source = a.wizard / 'tools/rpg_inventory/assets'
dest = root / 'native/client/assets/wizard/inventory'
dest.mkdir(parents=True, exist_ok=True)
prefixes = ('spear_', 'wrap_', 'crest_', 'ring_', 'hideshield_', 'mantle_',
            'sandals_', 'bracers_', 'girdle_', 'gorget_')
names = sorted(x.name for x in source.glob('*.png')
               if x.name.startswith(prefixes) and 'candidate' not in x.name)
names += ['frame_ornate.png', 'slot_texture.png']
records = []
compat_commit = subprocess.check_output(['git','-C',str(a.wizard),'rev-parse','56b81ed'],text=True).strip()
compat_names = ['crest_bone.png','gorget_bone.png','gorget_amber.png',
                'grips_hide.png','grips_quilted.png','grips_bronzescale.png']
for name in names:
    data = (source / name).read_bytes()
    (dest / name).write_bytes(data)
    records.append({'file': name, 'source': 'tools/rpg_inventory/assets/' + name,
                    'sha256': hashlib.sha256(data).hexdigest()})
for name in compat_names:
    path = 'tools/rpg_inventory/assets/' + name
    data = subprocess.check_output(['git','-C',str(a.wizard),'show',compat_commit+':'+path])
    (dest / name).write_bytes(data)
    records.append({'file':name,'source':path,'source_commit':compat_commit,
                    'purpose':'Artwork for an existing native form/material retained in native/src/core.cpp; no content or balance changes',
                    'sha256':hashlib.sha256(data).hexdigest()})
names += compat_names
(dest / 'manifest.json').write_text(json.dumps({
    'source_repository': 'https://github.com/alexkorol/WIZARD',
    'source_commit': '00be6a0fe4ecfbd0b7862249012308268f92f0d7',
    'conversion': 'byte-for-byte PNG copy; no pixelization, crop or recoloring',
    'layout_source': 'tools/rpg_inventory/index.html .doll-wrap / .doll-col / .pack-grids',
    'assets': records}, indent=2) + '\n')
header = '// Generated by native/tools/import-inventory-art.py.\n'
header += 'static constexpr const char* kInventoryArtFiles[] = {\n'
header += ''.join('    "' + n + '",\n' for n in names if n not in ('frame_ornate.png','slot_texture.png'))
header += '};\n'
(root / 'native/client/inventory_art_files.hpp').write_text(header)
print(f'Imported {len(records)} unchanged WIZARD PNGs')
