"""Build the bundled CC0 sans face; requires fontTools, only at asset-authoring time."""
from pathlib import Path
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
assets = root / "client/assets/fonts/sans"
font = TTFont(assets / "source/PixelOperatorHB.ttf", recalcTimestamp=False)
cmap = font.getBestCmap()
# Compatible punctuation aliases use this family's own glyphs. No OS fallback.
aliases = {0x2018: ord("'"), 0x2019: ord("'"), 0x201a: ord("'"),
           0x201c: ord('"'), 0x201d: ord('"'), 0x201e: ord('"'),
           0xa0: ord(' '), 0xad: ord('-')}
for table in font['cmap'].tables:
    if table.isUnicode():
        for dest, source in aliases.items():
            table.cmap.setdefault(dest, cmap[source])
for name in font['name'].names:
    values = {1: 'Verdigris Sans', 2: 'Regular', 3: 'VerdigrisSans-1',
              4: 'Verdigris Sans', 6: 'VerdigrisSans'}
    if name.nameID in values:
        name.string = values[name.nameID].encode(name.getEncoding())
font.save(assets / 'VerdigrisSans.ttf')
points = sorted(font.getBestCmap())
rows = [', '.join(f'0x{v:04x}' for v in points[i:i+12]) for i in range(0,len(points),12)]
(root / 'client/ui_font_coverage.hpp').write_text(
    '// Generated by native/tools/prepare-ui-font.py.\n#pragma once\n'
    'inline constexpr unsigned int kUiFontCodepoints[] = {\n  '
    + ',\n  '.join(rows) + '\n};\n', encoding='utf-8')
print(f'Bundled Verdigris Sans: {len(points)} mapped characters')
